apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
        - name: book-catalog
          image: apurv21/book-catalog:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: "postgresql://sit722_part2_db_user:quBAHt39TXmOZemleYmXGztpVl93PFI3@dpg-crcq9iij1k6c73crekv0-a.oregon-postgres.render.com/sit722_part2_db"
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  selector:
    app: book-catalog
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30001  # NodePort for accessing the service externally
